[training]
experiment_name = "stability_seed_123"
seed = 123
multiple_seeds = true

[model]
backbone_name = "EVA-02"

[optimizer]
type = "Adam"

[scheduler]
type = "JaguardIdScheduler"

[output]
profile = "stability"
experiment_group = "kaggle_stability"

[data]
split_data_path = "/splits/strclosed_set__dupFalse__kTrain3__kVal3__p4/full_split.parquet"
