[evaluation]
experiment_name = "class_attribution_class_faith_sanity_complex"

[xai_metrics]
source_type = "class_attribution"
source_run_dir = "eda_xai_class_attribution/eva02_val_n332_all_groups"

[output]
profile = "xai"
experiment_group = "eda_xai_metrics"
