[ensemble]
name = "single_eva02"
gallery_protocol = "both"       # "valonly_gallery"

[output]
experiment_group = "ensemble"

[fusion]
weights = [1.0]
normalize_mode = "global_minmax"           #  "none", "global_minmax", "row_minmax", "row_zscore"
square_before_fusion = true

[split]
include_duplicates = true
seed = 51

[data]
split_data_path = "splits/strclosed_set__dupFalse__kTrain3__kVal3__p4/full_split.parquet"
dataset_name = "jaguar_stage0"
num_workers = 8
use_fiftyone = false

[[members]]
name = "EVA-02"
checkpoint_path = "kaggle_backbone/backbone_eva02"
config_path = "kaggle_backbone/backbone_eva02/config_leaderboard_exp.toml"
cache_prefix = "backbone_eva02"

[[members]]
name = "MiewID"
checkpoint_path = "kaggle_backbone/backbone_miew_id"
config_path = "kaggle_backbone/backbone_miew_id/config_leaderboard_exp.toml"
cache_prefix = "backbone_miew_id"

[[members]]
name = "ConvNeXt-V2"
checkpoint_path = "kaggle_backbone/backbone_convnext_v2"
config_path = "kaggle_backbone/backbone_convnext_v2/config_leaderboard_exp.toml"
cache_prefix = "backbone_convnext_v2"

# [[members]]
# name = "DINOv2-Base"
# checkpoint_path = "kaggle_backbone/backbone_dinov2_base"
# config_path = "kaggle_backbone/backbone_dinov2_base/config_leaderboard_exp.toml"
# cache_prefix = "backbone_dinov2_base"

# [[members]]
# name = "MegaDescriptor-L"
# checkpoint_path = "kaggle_backbone/backbone_megadescriptor_l"
# config_path = "kaggle_backbone/backbone_megadescriptor_l/config_leaderboard_exp.toml"
# cache_prefix = "backbone_megadescriptor_l"

# [[members]]
# name = "Swin-Transformer"
# checkpoint_path = "kaggle_backbone/backbone_swin_transformer"
# config_path = "kaggle_backbone/backbone_swin_transformer/config_leaderboard_exp.toml"
# cache_prefix = "backbone_swin_transformer"

[inference]
batch_size = 64
use_tta = true
use_qe = false
use_rerank = false

[logging]
enabled = false
mode = "online"