[model]
backbone_name = "EVA-02"   # Options: "EVA-02", "MegaDescriptor-L", "MiewID", "DINO-Small", "DINOv2-Base", "ConvNeXt-V2", "EfficientNet-B4", "Swin-Transformer" 
head_type = "triplet"   # Options: "arcface"
emb_dim = 1024
freeze_backbone = true
s = 30.0
m = 0.7 #m = 0.50
use_projection = true
use_forward_features = false
mining_type = "hard"

[split]
strategy = "closed_set"
val_split_size = 0.2   #0.2 round_2, 0.05 round_1
include_duplicates = false
seed = 42

[data]
split_data_path = "/splits/strclosed_set__dupFalse__kTrain3__kVal3__p4/full_split.parquet"
# split_data_path = "/splits/strclosed_set__dupTrue__kTrain1__kVal50__p4/full_split.parquet"
# split_data_path = "/splits/default_kaggle/full_split.parquet"
dataset_name = "jaguar_stage0"
use_balanced_sampler = false    # Set to true to handle class imbalance
num_workers = 32

[curation]
train_k = 1
val_k = 30    #50
phash_threshold = 4

[preprocessing]
train_background = "original"
val_background = "original"
bg_dir = "data/round_2/backgrounds"
p_original = 0.5
edge_softness = 2
blur_radius = 10
key_for_seed = "filename"

[training]
monitor_metric = "pairwise_AP"      # Options: "mAP"; "pairwise_AP"
save_dir = "/fast/AG_Kainmueller/data/jaguar_project/jaguar_checkpoints/round_1/" 
# save_dir = "checkpoints/round_2/"  
experiment_name = "kaggle_base"
epochs = 30
batch_size = 32  # 16
samples_per_class = 4
seed = 42
early_stopping = true
early_stopping_patience = 5
# ---Fine-tuning Params---
unfreeze_epoch = 5       # At epoch 5, start training part of the backbone; ; if set to 0 the backbone stays frozen
unfreeze_blocks = 2      # Number of blocks (from the end) to unfreeze; if set to 0 the backbone stays frozen
# ---EMA Params---
ema = false
ema_decay = 0.995

[optimizer]
type = "Adam"         # Options: "Adam", "AdamW", "SGD", "Lion", "Muon" etc.
lr = 1e-5              # lr_start = 1e-5 for custom scheduler; 2e-5 for AdamW
lr_muon = 0.005        # Muon branch; backbone weights
weight_decay = 1e-3
momentum = 0.9          # Only used for SGD
betas = [0.9, 0.999]    # Only used for Adam/AdamW
backbone_lr = 2e-6       # Keep this very small (1/10th or 1/100th of head LR)
factor = 0.1             # ReduceLROnPlateau
patience = 2             # ReduceLROnPlateau

[scheduler]
type = "JaguardIdScheduler"  # Options: "CosineAnnealingLR", "OneCycleLR", "ReduceLROnPlateau", "JaguardIdScheduler"
T_max = 30                  # CosineAnnealingLR
lr_start = 1e-5             # custom 
lr_min = 9e-6               # Cosine or custom or ReduceLROnPlateau
lr_max = 1e-3               # Custom or OneCycle
lr_ramp_ep = 15             # Custom
lr_sus_ep = 0               # Custom
lr_decay = 0.8              # Custom

[augmentation]
apply_augmentations = true
horizontal_flip = true
random_resized_crop = false
gaussian_blur = false
affine_degrees = 15
affine_translate = [0.15, 0.15]
affine_scale = [0.85, 1.15]
color_jitter_brightness = 0.2
color_jitter_contrast = 0.2
random_erasing_p = 0.25

[mining_analysis]
silhouette_freq = 5         # Compute Silhouette and refresh viz data every x epochs if force_silhouette true
force_silhouette = false    # Set to true for the mining RQ study

[rare_identity_eval]
enabled = false
threshold = 50

[evaluation]
extra_val_backgrounds = ["original", "gray_bg"]
apply_tta = true
tta_modality = flip   # Options: "tta", "multiscale" only compatible with backbone_name in ["ConvNeXt-V2", "EfficientNet-B4"]
apply_qe = true
top_k_expansion = 3
apply_rerank = false 

[xai]
seed = 42
n_samples = 100
ig_steps = 10

[progressive_resizing]
enabled = false
stage_epochs = []       # [10, 10, 10]

[logging]
enabled = true
project = "jaguar-reid"
mode = "online"