[experiment]
name = "xai_base"
mode = "explain"
# type = "similarity"
setup_name = "eda_base"          # hier braucht es noch eigenes setup!
output_profile = "xai"

[inference]
batch_size = 64
use_tta = false
use_qe = false
use_rerank = false

[evaluation]
checkpoint_dir = "inference_model"       

[data]
num_workers = 4
split_data_path = "splits/strclosed_set__dupFalse__kTrain3__kVal1__p4/full_split.parquet"

[split]
include_duplicates = false

[xai]
dataset_name = "jaguar_splits_curated"
split_name = "val"
n_samples = 50      # "full"
seed = 51
explainer_names = ["IG", "GradCAM"]
pair_types = ["easy_pos", "hard_neg"]

ig_steps = 50
ig_internal_bs = 64
ig_batch_size = 64


[xai_metrics.faithfulness]
steps = 30
baseline = "blur"          # "blur", "zeros"
use_abs = true

[xai_metrics.complexity]
abs = true
normalise = true
display_progressbar = true


[logging]
enabled = true
project = "jaguar-reid-SpotItLikeItsHot"
mode = "online"