[inference]
batch_size = 64
use_tta = false
use_qe = false
use_rerank = false

[evaluation]
checkpoint_dir = "inference_model"     

[preprocessing]
bg_dir = "backgrounds"
train_background = "original"
val_background = "original"
p_original = 0.5
edge_softness = 2
blur_radius = 10
key_for_seed = "filename"

[data]
num_workers = 4
split_data_path = "splits/strclosed_set__dupTrue__kTrain1__kVal50__p4/full_split.parquet"
use_fiftyone = true

[split]
include_duplicates = true
seed = 51

[xai]
dataset_name = "jaguar_splits_curated"
split_name = "val"
n_samples = 332      # "full" 150
seed = 51
explainer_names = ["GradCAM", "IG"]
pair_types = ["easy_pos", "hard_neg", "hard_pos"]
groups = ["all", "orig_rank1_correct", "orig_rank1_wrong"]

ig_steps = 50
ig_internal_bs = 64
ig_batch_size = 64


[xai_metrics.faithfulness]
steps = 30
baseline = "blur"          # "blur", "zeros"
use_abs = true

[xai_metrics.complexity]
abs = true
normalise = true
display_progressbar = true


[logging]
enabled = true
mode = "online"