#!/usr/bin/env bash
set -e

python src/jaguar/experiments/run_ensemble.py --base_config base/ensemble_base --experiment_config _generated/kaggle_ensemble/eva_miew_convnext_equal_globalminmax_sq --experiment_name eva_miew_convnext_equal_globalminmax_sq

python src/jaguar/experiments/run_ensemble.py --base_config base/ensemble_base --experiment_config _generated/kaggle_ensemble/eva_miew_convnext_equal_globalminmax_nosq --experiment_name eva_miew_convnext_equal_globalminmax_nosq

python src/jaguar/experiments/run_ensemble.py --base_config base/ensemble_base --experiment_config _generated/kaggle_ensemble/eva_miew_convnext_equal_rowminmax_sq --experiment_name eva_miew_convnext_equal_rowminmax_sq

python src/jaguar/experiments/run_ensemble.py --base_config base/ensemble_base --experiment_config _generated/kaggle_ensemble/eva_miew_convnext_evaheavy_globalminmax_sq --experiment_name eva_miew_convnext_evaheavy_globalminmax_sq

python src/jaguar/experiments/run_ensemble.py --base_config base/ensemble_base --experiment_config _generated/kaggle_ensemble/eva_miew_convnext_miewheavy_globalminmax_sq --experiment_name eva_miew_convnext_miewheavy_globalminmax_sq

python src/jaguar/experiments/run_ensemble.py --base_config base/ensemble_base --experiment_config _generated/kaggle_ensemble/eva_miew_convnext_convnextheavy_globalminmax_sq --experiment_name eva_miew_convnext_convnextheavy_globalminmax_sq

python src/jaguar/experiments/run_ensemble.py --base_config base/ensemble_base --experiment_config _generated/kaggle_ensemble/eva_miew_convnext_eva_miew_favored_globalminmax_sq --experiment_name eva_miew_convnext_eva_miew_favored_globalminmax_sq

