[ensemble]
name = "single_dinov2_base"

[output]
profile = "ensemble"
experiment_group = "kaggle_ensemble"

[[members]]
name = "DINOv2-Base"
checkpoint_path = "kaggle_backbone/backbone_dinov2_base"
config_path = "kaggle_backbone/backbone_dinov2_base/config_leaderboard_exp.toml"
cache_prefix = "backbone_dinov2_base"
