[ensemble]
name = "single_eva02"

[output]
profile = "ensemble"
experiment_group = "kaggle_ensemble"

[[members]]
name = "EVA-02"
checkpoint_path = "kaggle_backbone/backbone_eva02"
config_path = "kaggle_backbone/backbone_eva02/config_leaderboard_exp.toml"
cache_prefix = "backbone_eva02"
