[training]
experiment_name = "adam__JaguardIdScheduler"
seed = 512
multiple_seeds = true

[optimizer]
type = "Adam"
lr = 1e-05
weight_decay = 0.001
betas = [0.9, 0.999]

[scheduler]
type = "JaguardIdScheduler"
lr_max = 0.001

[output]
profile = "optim_sched"
experiment_group = "kaggle_optim_sched"

[data]
split_data_path = "/splits/strclosed_set__dupFalse__kTrain3__kVal3__p4/full_split.parquet"
