[training]
experiment_name = "loss_triplet"

[model]
head_type = "triplet"
m = 0.5
mining_type = "semi-hard"

[mining_analysis]
silhouette_freq = 5
force_silhouette = true

[output]
profile = "mining"
experiment_group = "kaggle_mining"

[data]
split_data_path = "/splits/strclosed_set__dupFalse__kTrain3__kVal3__p4/full_split.parquet"
