[training]
experiment_name = "baseline_init"

[model]
head_type = "arcface"
m = 0.5

[split]
include_duplicates = true

[optimizer]
type = "Adam"
lr = 0.001
weight_decay = 0.0001
momentum = 0.9
betas = [0.9, 0.999]

[scheduler]
type = "CosineAnnealingLR"
T_max = 30
lr_start = 1e-05
lr_min = 9e-06
lr_max = 0.001

[augmentation]
apply_augmentations = false

[output]
profile = "baseline"
experiment_group = "baseline"

[data]
split_data_path = "splits/strclosed_set__dupTrue__kTrain1__kVal50__p4/full_split.parquet"
