[training]
experiment_name = "fixed_cnv2_unfreeze_4_largerlr"
unfreeze_epoch = 3
unfreeze_blocks = 4
epochs = 50

[model]
backbone_name = "ConvNeXt-V2"
s = 40
m = 0.4

[progressive_resizing]
enabled = false

[augmentation]
random_resized_crop = true

[output]
profile = "resizing"
experiment_group = "kaggle_progressive_resizing"

[data]
split_data_path = "/splits/strclosed_set__dupFalse__kTrain3__kVal3__p4/full_split.parquet"
