[training]
experiment_name = "no_progressive_cnv2"
unfreeze_blocks = 100
epochs = 50
seed = 42
multiple_seeds = false

[model]
backbone_name = "ConvNeXt-V2"
m = 0.7

[progressive_resizing]
enabled = false

[augmentation]
random_resized_crop = true

[output]
profile = "resizing"
experiment_group = "kaggle_progressive_resizing"

[data]
split_data_path = "/splits/strclosed_set__dupFalse__kTrain3__kVal3__p4/full_split.parquet"
