[model]
backbone_name = "EVA-02"
head_type = "arcface" # head+loss criterion
emb_dim = 1024
freeze_backbone = true  # To unfreeze the backbone, set other relative parameters accordingly in [training]
s = 30.0
m = 0.50

[data]
dataset_name = "jaguar_stage0"
parquet_path = "splits/jaguar_burst__str_closed_set__pol_drop_duplicates__k1/full_split.parquet"
val_split = 0.05     #0.2
# Set to true to handle class imbalance
use_balanced_sampler = false
num_workers = 32
full_ds = true
include_duplicates = true

[training]
monitor_metric = "pairwise_AP"      # Options: "mAP", "pairwise_AP" 
save_dir = "/media/vanessa/UBUNTU1/home/vanessa/Documents/jaguar_checkpoints/"
experiment_name = "round_eva_baseline_no_bs_vs_005_pairwiseAP_finetuningbackbone_cosineannealing"
# config_folder = "megadescriptor"
epochs = 30
batch_size = 16
seed = 42
early_stopping = true
early_stopping_patience = 5
# ---Fine-tuning Params---
unfreeze_epoch = 5       # At epoch 5, start training part of the backbone; ; if set to 0 the backbone stays frozen
unfreeze_blocks = 2      # Number of blocks (from the end) to unfreeze; if set to 0 the backbone stays frozen

[optimizer]
type = "Adam"         # Options: "Adam", "AdamW", "SGD", "Lion", "Muon" etc.
lr = 1e-5              # lr_start = 1e-5 for custom scheduler; 2e-5 for AdamW
weight_decay = 1e-3
momentum = 0.9          # Only used for SGD
betas = [0.9, 0.999]    # Only used for Adam/AdamW
backbone_lr = 2e-6       # Keep this very small (1/10th or 1/100th of head LR)

[scheduler]
type = "JaguardIdScheduler"  # Options: "CosineAnnealingLR", "OneCycleLR", "ReduceLROnPlateau", "JaguardIdScheduler"
T_max = 30                  # CosineAnnealingLR
lr_start = 1e-5             # custom 
lr_min = 9e-6               # Cosine or custom
lr_max = 1e-3               # Custom or OneCycle
lr_ramp_ep = 15             # Custom
lr_sus_ep = 0               # Custom
lr_decay = 0.8              # Custom

[augmentation]
apply_augmentations = true
horizontal_flip = true
affine_degrees = 15
affine_translate = [0.15, 0.15]
affine_scale = [0.85, 1.15]
color_jitter_brightness = 0.2
color_jitter_contrast = 0.2
random_erasing_p = 0.25