[evaluation]
experiment_name = "fg_contribution_megadescriptor_base"
checkpoint_dir = "triplet_loss/backbone_megadescriptor_l"

[output]
profile = "xai"
experiment_group = "eda_foreground_contribution"
