[training]
experiment_name = "closed_curated_traink_8_valk_1_p4"

[split]
strategy = "closed_set"
include_duplicates = false

[curation]
train_k = 8
val_k = 1
phash_threshold = 4

[output]
profile = "deduplication"
experiment_group = "kaggle_deduplication"

[data]
split_data_path = "splits/strclosed_set__dupFalse__kTrain8__kVal1__p4/full_split.parquet"
