[training]
experiment_name = "closed_keep_all"

[split]
strategy = "closed_set"
include_duplicates = true

[output]
profile = "deduplication"
experiment_group = "kaggle_deduplication"

[data]
split_data_path = "splits/strclosed_set__dupTrue__kTrain1__kVal50__p4/full_split.parquet"
