[training]
experiment_name = "backbone_dinov2_for_wildlife"

[model]
backbone_name = "DINOv2_for_wildlife"

[output]
profile = "backbone"
experiment_group = "kaggle_backbone"

[data]
split_data_path = "splits/strclosed_set__dupFalse__kTrain3__kVal1__p4/full_split.parquet"
