[training]
experiment_name = "backbone_megadescriptor_l"
seed = 42
multiple_seeds = false

[model]
backbone_name = "MegaDescriptor-L"

[output]
profile = "backbone"
experiment_group = "kaggle_backbone"

[data]
split_data_path = "/splits/strclosed_set__dupFalse__kTrain3__kVal3__p4/full_split.parquet"
