[training]
experiment_name = "backbone_dinov2_base"

[model]
backbone_name = "DINOv2-Base"

[output]
profile = "backbone"
experiment_group = "kaggle_backbone"

[data]
split_data_path = "splits/default_kaggle/full_split.parquet"
