[training]
experiment_name = "aug_flip_only"

[augmentation]
apply_augmentations = true
horizontal_flip = true
random_resized_crop = false
gaussian_blur = false
affine_degrees = 0
color_jitter_brightness = 0
color_jitter_contrast = 0
random_erasing_p = 0

[output]
profile = "augmentation"
experiment_group = "kaggle_augmentation"

[data]
split_data_path = "/splits/strclosed_set__dupFalse__kTrain3__kVal3__p4/full_split.parquet"
