[training]
experiment_name = "aug_geom_noerase"
seed = 42
multiple_seeds = false

[augmentation]
apply_augmentations = true
horizontal_flip = true
random_resized_crop = true
gaussian_blur = false
affine_degrees = 15
affine_translate = [0.15, 0.15]
affine_scale = [0.85, 1.15]
color_jitter_brightness = 0.2
color_jitter_contrast = 0.2
random_erasing_p = 0

[output]
profile = "augmentation"
experiment_group = "kaggle_augmentation"

[data]
split_data_path = "/splits/strclosed_set__dupFalse__kTrain3__kVal3__p4/full_split.parquet"
